#!/bin/bash
# Get all process IDs that match the window class of "Minecraft"
pids=$(xdotool search --class "Minecraft")

# Loop them to find the valid window
for pid in $pids; do
  name=$(xdotool getwindowname $pid)

  if [[ $name == *"Minecraft"* ]]; then
    # Convert decimal PID to hexadecimal
    window_id=$(printf 0x"%x\n" $pid)

    # Start clicking!
    xdotool mousedown --window $window_id 3

    # Stop looping
    break
  fi
done
